### ISSUE TITLE
How to solve "-72008" error?

### ISSUE THREAD

**Issue by SaintZhao** [szt243660543/ARMultiuser#1]
Hi, sorry to bother you!
When i run this app from xcode，we see some error as below：

2021-02-03 18:07:49.465597+0800 ARMultiuser[32211:1416873] [MCNearbyServiceAdvertiser] Server did not publish: errorDict [{
    NSNetServicesErrorCode = "-72008";
    NSNetServicesErrorDomain = 10;
}].

How can i solve this error? Thank you!

**Comment by szt243660543** [comment]
解决方法：https://blog.csdn.net/weixin_39404995/article/details/113242547

**Comment by SaintZhao** [comment]
非常感谢，问题已解决。
